#!/usr/bin/env node
/**
 * Compiles filters/<list>.txt into:
 *
 *   Chrome extension
 *     extension/generated/rulesets/<list>.json   declarativeNetRequest static rulesets
 *     extension/generated/cosmetic-data.js       element-hiding data for the content script
 *     extension/generated/list-stats.json        rule counts shown on the options page
 *
 *   Android app (DNS-level blocking, so only whole-domain filters are used)
 *     android/app/src/main/assets/filters/<list>.txt   one domain per line, `@@` = exception
 *     android/app/src/main/assets/filters/index.json   list metadata
 *
 * Usage:
 *   node scripts/build.mjs            write the files
 *   node scripts/build.mjs --check    fail if the committed files are stale (CI)
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { DEFAULT_SETTINGS, FILTER_LISTS } from '../extension/src/shared/defaults.js';
import { compileNetworkRules, parseFilterList } from '../extension/src/shared/filter-parser.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const EXTENSION = 'extension';
const ANDROID_ASSETS = 'android/app/src/main/assets/filters';
const CHECK = process.argv.includes('--check');

// Chrome guarantees at least this many enabled static rules / regex rules.
const LIMITS = { staticRules: 30_000, regexRules: 1_000 };

const problems = [];
const outputs = new Map();

const manifest = JSON.parse(await readFile(path.join(ROOT, EXTENSION, 'manifest.json'), 'utf8'));
const resources = manifest.declarative_net_request?.rule_resources ?? [];

const cosmetic = {};
const listStats = {};
const androidIndex = [];
let totalRules = 0;
let totalRegex = 0;

for (const list of FILTER_LISTS) {
  const source = path.join('filters', `${list.id}.txt`);
  const parsed = parseFilterList(await readFile(path.join(ROOT, source), 'utf8'));
  for (const e of parsed.errors) problems.push(`${source}:${e.line}: ${e.message}\n    ${e.text}`);

  const rules = compileNetworkRules(parsed.network).map((c) => c.rule);
  const resource = resources.find((r) => r.id === list.id);
  if (!resource) {
    problems.push(`extension/manifest.json: missing rule_resources entry for "${list.id}"`);
    continue;
  }
  if (resource.enabled !== list.enabledByDefault) {
    problems.push(`extension/manifest.json: ruleset "${list.id}" enabled=${resource.enabled}, defaults.js says ${list.enabledByDefault}`);
  }
  outputs.set(path.posix.join(EXTENSION, resource.path), rulesToJson(rules));

  const c = parsed.cosmetic;
  const cosmeticCount = c.generic.length + countValues(c.byHost);
  if (cosmeticCount || countValues(c.exceptions)) cosmetic[list.id] = c;

  listStats[list.id] = { networkFilters: parsed.network.length, networkRules: rules.length, cosmeticFilters: cosmeticCount };
  totalRules += rules.length;
  totalRegex += rules.filter((r) => r.condition.regexFilter).length;

  const dns = domainRules(rules);
  if (dns.blocked.length || dns.allowed.length) {
    outputs.set(`${ANDROID_ASSETS}/${list.id}.txt`, domainsToText(list, dns));
    androidIndex.push({
      id: list.id,
      title: list.title,
      description: list.androidDescription ?? list.description,
      enabledByDefault: list.enabledByDefault,
      domains: dns.blocked.length,
    });
  }

  console.log(
    `${list.id.padEnd(11)} ${String(parsed.network.length).padStart(4)} network filters → ${String(rules.length).padStart(3)} rules, ` +
      `${String(cosmeticCount).padStart(3)} cosmetic filters, ${String(dns.blocked.length).padStart(3)} DNS domains`,
  );
}

for (const r of resources) {
  if (!FILTER_LISTS.some((l) => l.id === r.id)) problems.push(`extension/manifest.json: ruleset "${r.id}" has no entry in FILTER_LISTS`);
}
if (totalRules > LIMITS.staticRules) problems.push(`Too many static rules: ${totalRules} > ${LIMITS.staticRules}`);
if (totalRegex > LIMITS.regexRules) problems.push(`Too many regex rules: ${totalRegex} > ${LIMITS.regexRules}`);

outputs.set(
  `${EXTENSION}/generated/cosmetic-data.js`,
  '// Generated by scripts/build.mjs from filters/*.txt. Do not edit by hand.\n' +
    `globalThis.ADBLOCKER_DATA = ${JSON.stringify({ defaults: DEFAULT_SETTINGS, lists: cosmetic }, null, 2)};\n`,
);
outputs.set(`${EXTENSION}/generated/list-stats.json`, `${JSON.stringify(listStats, null, 2)}\n`);
outputs.set(`${ANDROID_ASSETS}/index.json`, `${JSON.stringify(androidIndex, null, 2)}\n`);

if (problems.length) {
  console.error(`\n${problems.length} problem(s):\n${problems.join('\n')}`);
  process.exit(1);
}

if (CHECK) {
  const stale = [];
  for (const [file, content] of outputs) {
    const current = await readFile(path.join(ROOT, file), 'utf8').catch(() => null);
    if (current?.replace(/\r\n/g, '\n') !== content) stale.push(file);
  }
  if (stale.length) {
    console.error(`\nGenerated files are out of date, run \`npm run build\`:\n  ${stale.join('\n  ')}`);
    process.exit(1);
  }
  console.log('\nGenerated files are up to date.');
} else {
  for (const [file, content] of outputs) {
    await mkdir(path.dirname(path.join(ROOT, file)), { recursive: true });
    await writeFile(path.join(ROOT, file), content);
  }
  console.log(`\nWrote ${outputs.size} files (${totalRules} static rules).`);
}

function rulesToJson(rules) {
  // One rule per line keeps diffs of the generated files readable.
  return rules.length ? `[\n${rules.map((r) => `  ${JSON.stringify(r)}`).join(',\n')}\n]\n` : '[]\n';
}

function countValues(record) {
  return Object.values(record).reduce((n, list) => n + list.length, 0);
}

/**
 * DNS can only see hostnames, so only rules that match a whole domain with no
 * other condition (no path, resource type or party option) carry over.
 */
function domainRules(rules) {
  const pick = (type) =>
    rules
      .filter((r) => r.action.type === type && Object.keys(r.condition).join() === 'requestDomains')
      .flatMap((r) => r.condition.requestDomains);
  return { blocked: [...new Set(pick('block'))].sort(), allowed: [...new Set(pick('allow'))].sort() };
}

function domainsToText(list, { blocked, allowed }) {
  return [
    `# ${list.title}. Generated by scripts/build.mjs from filters/${list.id}.txt. Do not edit by hand.`,
    ...blocked,
    ...allowed.map((d) => `@@${d}`),
    '',
  ].join('\n');
}
