#!/usr/bin/env node
/**
 * Compiles filters/<list>.txt into:
 *   generated/rulesets/<list>.json   declarativeNetRequest static rulesets
 *   generated/cosmetic-data.js       element-hiding data for the content script
 *   generated/list-stats.json        rule counts shown on the options page
 *
 * Usage:
 *   node scripts/build.mjs            write the files
 *   node scripts/build.mjs --check    fail if the committed files are stale (CI)
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { DEFAULT_SETTINGS, FILTER_LISTS } from '../src/shared/defaults.js';
import { compileNetworkRules, parseFilterList } from '../src/shared/filter-parser.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

// Chrome guarantees at least this many enabled static rules / regex rules.
const LIMITS = { staticRules: 30_000, regexRules: 1_000 };

const problems = [];
const outputs = new Map();

const manifest = JSON.parse(await readFile(path.join(ROOT, 'manifest.json'), 'utf8'));
const resources = manifest.declarative_net_request?.rule_resources ?? [];

const cosmetic = {};
const listStats = {};
let totalRules = 0;
let totalRegex = 0;

for (const list of FILTER_LISTS) {
  const source = path.join('filters', `${list.id}.txt`);
  const parsed = parseFilterList(await readFile(path.join(ROOT, source), 'utf8'));
  for (const e of parsed.errors) problems.push(`${source}:${e.line}: ${e.message}\n    ${e.text}`);

  const rules = compileNetworkRules(parsed.network).map((c) => c.rule);
  const resource = resources.find((r) => r.id === list.id);
  if (!resource) {
    problems.push(`manifest.json: missing rule_resources entry for "${list.id}"`);
    continue;
  }
  if (resource.enabled !== list.enabledByDefault) {
    problems.push(`manifest.json: ruleset "${list.id}" enabled=${resource.enabled}, defaults.js says ${list.enabledByDefault}`);
  }
  outputs.set(resource.path, rulesToJson(rules));

  const c = parsed.cosmetic;
  const cosmeticCount = c.generic.length + countValues(c.byHost);
  if (cosmeticCount || countValues(c.exceptions)) cosmetic[list.id] = c;

  listStats[list.id] = { networkFilters: parsed.network.length, networkRules: rules.length, cosmeticFilters: cosmeticCount };
  totalRules += rules.length;
  totalRegex += rules.filter((r) => r.condition.regexFilter).length;

  console.log(
    `${list.id.padEnd(11)} ${String(parsed.network.length).padStart(4)} network filters → ${String(rules.length).padStart(3)} rules, ` +
      `${String(cosmeticCount).padStart(3)} cosmetic filters`,
  );
}

for (const r of resources) {
  if (!FILTER_LISTS.some((l) => l.id === r.id)) problems.push(`manifest.json: ruleset "${r.id}" has no entry in FILTER_LISTS`);
}
if (totalRules > LIMITS.staticRules) problems.push(`Too many static rules: ${totalRules} > ${LIMITS.staticRules}`);
if (totalRegex > LIMITS.regexRules) problems.push(`Too many regex rules: ${totalRegex} > ${LIMITS.regexRules}`);

outputs.set(
  'generated/cosmetic-data.js',
  '// Generated by scripts/build.mjs from filters/*.txt. Do not edit by hand.\n' +
    `globalThis.ADBLOCKER_DATA = ${JSON.stringify({ defaults: DEFAULT_SETTINGS, lists: cosmetic }, null, 2)};\n`,
);
outputs.set('generated/list-stats.json', `${JSON.stringify(listStats, null, 2)}\n`);

if (problems.length) {
  console.error(`\n${problems.length} problem(s):\n${problems.join('\n')}`);
  process.exit(1);
}

if (CHECK) {
  const stale = [];
  for (const [file, content] of outputs) {
    const current = await readFile(path.join(ROOT, file), 'utf8').catch(() => null);
    if (current?.replace(/\r\n/g, '\n') !== content) stale.push(file);
  }
  if (stale.length) {
    console.error(`\nGenerated files are out of date, run \`npm run build\`:\n  ${stale.join('\n  ')}`);
    process.exit(1);
  }
  console.log('\nGenerated files are up to date.');
} else {
  for (const [file, content] of outputs) {
    await mkdir(path.dirname(path.join(ROOT, file)), { recursive: true });
    await writeFile(path.join(ROOT, file), content);
  }
  console.log(`\nWrote ${outputs.size} files (${totalRules} static rules).`);
}

function rulesToJson(rules) {
  // One rule per line keeps diffs of the generated files readable.
  return rules.length ? `[\n${rules.map((r) => `  ${JSON.stringify(r)}`).join(',\n')}\n]\n` : '[]\n';
}

function countValues(record) {
  return Object.values(record).reduce((n, list) => n + list.length, 0);
}
